# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

# !!!!! FILE predstavuje DOCKER BUILD PIPELINE, ktora vykona vytvori DOCKER IMAGE a vlozi ho do AZURE CONTAINER REGISTRY.

name: My DOCKER BUILD and PUBLISH to AZURE.

on:
  push:
    branches: [ "main" ]


jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    # !!!!! ENVIRONMENT sa nastavuje, pretoze sa do ENVIRONMENT uklada USER NAME a PASSWORD do AZURE CONTAINER REGISTRY.
    environment: Production

    steps:
    # !!!!! Nastavi sa ENVIRONMENT na .NET 8.0..
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # !!!!! Stiahnu sa DEPENDENCIES pre .NET 8.0..
    - name: Restore dependencies
      run: dotnet restore

    # !!!!! Spustia sa testy PROGRAMU.
    - name: Build
      run: dotnet build --no-restore


